name: CODEFLIX | Sol Lopez
title: CODEFLIX | Sol Lopez
description: 
tags:
  - blog
  - coding
  - jekyll
  - angular
  - codeflix
email: test@xyz.com
disqus_username: sol
show_hero: true
menu:
  - title: Home
    url: /

