name: Feliz lectura y programacion!
title: Feliz lectura y programacion! | Sol Lopez
description: 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: test@xyz.com
disqus_username: sol
show_hero: true
menu:
  - title: Home
    url: /

