name: CODEFLIX | Sol Lopez
title: CODEFLIX | Sol Lopez
language: es
description: 
tags:
  - blog
  - coding
  - jekyll
  - angular
  - codeflix
email: ingsollopez@gmail.com
disqus_username: sol
show_hero: true
menu:
  - title: Home
    url: /
  - title: About Me
    url: https://solopez.github.io/sol/ 
  - title: My Github
    url: https://github.com/solopez
  - title: Coffee or Beer?
    url: https://cafecito.app/codeflixbysollopez
