name: CODEFLIX | Sol Lopez
title: CODEFLIX | Sol Lopez
language: en
description: 
tags:
  - blog
  - coding
  - jekyll
  - angular
  - codeflix
email: ingsollopez@gmail.com
disqus_username: sol
show_hero: true
menu:
  - title: Home
    url: /
  - title: My Github
    url: https://github.com/solopez
